name: 'Clean Up Organization Members'
description: 'Removes inactive members from a GitHub organization.'

branding:
  icon: 'file-text'
  color: 'yellow'

inputs:
  token:
    description: 'GitHub Token'
    required: true
  memberListPath:
    description: 'Path to the csv file containing the list of members in the organization.'
    required: true
  reportPath:
    description: 'Path to the directory where the csv file containing the inactive members should be saved.'
    required: true
  totalDaysInactive:
    description: 'Number of days a member must be inactive to be considered inactive.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
