name: 'Clean Up Organization Members'
description: 'Removes inactive members from a GitHub organization.'

branding:
  icon: 'file-text'
  color: 'yellow'

inputs:
  token:
    description: 'Personal Access Token (PAT) with the necessary permissions to remove members from the organization.'
    required: true
  member_list_path:
    description: 'Path to the csv file containing the list of members in the organization.'
    required: true
  report_path:
    description: 'Path to the directory where the csv file containing the summary of inactive members should be saved.'
    required: true
  total_days_inactive:
    description: 'Number of days a member must be inactive to be considered inactive.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
